### ISSUE TITLE
flax_stable_noClock.lua doesn't plant when walking South

### ISSUE THREAD

**Issue by Cegaiel** [DashingStrike/Automato-ATITD9#12]
Beware that on some lower resolutions, the icon tray at bottom might get in the way while walking south:

![image](https://user-images.githubusercontent.com/1331203/63486408-5f43b000-c475-11e9-94c2-03dd582dd582.png)

You might notice instead of planting it tries to gather grass, slate, etc.
In this case, you'll want to minimize this tray or choose F12 mode.

If your seed requires water, then this might not be best solution.  Note you can drag the icon tray to other locations.  Maybe bottom left corner might be a good place for it.

**Comment by vi-mikes** [comment]
Another clue the macro is clicking the icon tray.

![image](https://user-images.githubusercontent.com/11970767/64070429-4da89800-cc2d-11e9-8210-9ca58c76315c.png)

I'm using 1920x1080. I somehow had my icon tray not pushed flat against bottom border of game. See the gap in red box?  When I moved it all the way to bottom, I stopped having problems.

People with lower resolutions might not be able to get away with this. You still will likely need to minimize tray or move it to the left side of screen (no longer in center, where it can be clicked during the south walk.

Also note the popup window about Don't stack flax, it's an exploit.  That's another clue.  Since I was not able to walk south (due to misclick on my icon tray), then it tried to add another plant in my same location (hence causing the popup error).

In the past, I had added the "Extra spacing on Grid" checkbox to avoid this. But I see now, this new checkbox isn't needed at all; the misclick is the entire reason for this error ><

**Comment by vi-mikes** [comment]
Using F12 Mode will fix it for sure. But that's not helpful if you need the icon bar to appear to show the Water icon.


![image](https://user-images.githubusercontent.com/11970767/67637376-891fb580-f8b0-11e9-8535-e67d5c78b056.png)

One method is to move the icon bar slightly to left (so that the lowest part of bar, appears directly south of avatar.  This setup will possibly prevent a misclick on the top bar (in red rectangle box).

**Comment by KavadATITD** [comment]
Fixed this in flax_stable.lua by minimizing the tray before planting, and opening it back up afterward (for drawing water).
